version: '3.7'

services:

  omnomnom:
    command: bash -c "
        npm install
        && concurrently \"npm run start\" \"npm run watch-sass\"
      "
    container_name: "omnomnom"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node_modules:/usr/src/app/node_modules # cache
      - ./package.json:/usr/src/app/package.json
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports:
      - "3000:3000"
    user: "1000:1001"
    #environment:
      #CHOKIDAR_USEPOLLING: "true"
    stdin_open: true # docker run -i
    # tty: true        # docker run -t
    networks:
      - public
    restart: on-failure

networks:
  public:
    name: public
