version: '3.7'

services:

  omnomnom:
    command: bash -c "
        npm install
        && concurrently
            \"npm run start\"
            \"npm run watch-sass\"
            \"npm run storybook\"
            \"npm run watch-package\"
      "
    container_name: "omnomnom"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node_modules:/usr/src/app/node_modules # cache
      - ./package.json:/usr/src/app/package.json
      - ./src:/usr/src/app/src
      - ./.storybook:/usr/src/app/.storybook
      - ./public:/usr/src/app/public
    ports:
      - "3000:3000"
      - "3001:6006"
    user: "1000:1001"
    networks:
      - public
    restart: on-failure

networks:
  public:
    name: public
